
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package AnalisJson;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CADENA = 2;
  public static final int COMA = 4;
  public static final int COMENLI = 9;
  public static final int DOSPUNTOS = 8;
  public static final int EOF = 0;
  public static final int LLAVE_C = 7;
  public static final int LLAVE_A = 6;
  public static final int CADEN = 3;
  public static final int DOUBLEN = 5;
  public static final int error = 1;
  public static final int COMENMULTILI = 10;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CADENA",
  "CADEN",
  "COMA",
  "DOUBLEN",
  "LLAVE_A",
  "LLAVE_C",
  "DOSPUNTOS",
  "COMENLI",
  "COMENMULTILI"
  };
}

