
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analis;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MENOS = 5;
  public static final int PUNTOYCOMA = 14;
  public static final int CADENA = 25;
  public static final int IGUAL = 11;
  public static final int INT = 16;
  public static final int LETRA = 22;
  public static final int CHAR = 18;
  public static final int IDENTI = 15;
  public static final int DIVISION = 6;
  public static final int DOUBLEN = 21;
  public static final int TRUE = 23;
  public static final int IF = 13;
  public static final int POR = 3;
  public static final int STRING = 20;
  public static final int EOF = 0;
  public static final int MOSTRAR = 12;
  public static final int COMENMULTILI = 27;
  public static final int FALSE = 24;
  public static final int PARENTESIS_C = 8;
  public static final int error = 1;
  public static final int PARENTESIS_A = 7;
  public static final int LLAVE_C = 10;
  public static final int BOOL = 19;
  public static final int LLAVE_A = 9;
  public static final int ENTERO = 2;
  public static final int MAS = 4;
  public static final int COMENLI = 26;
  public static final int DOUBLE = 17;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ENTERO",
  "POR",
  "MAS",
  "MENOS",
  "DIVISION",
  "PARENTESIS_A",
  "PARENTESIS_C",
  "LLAVE_A",
  "LLAVE_C",
  "IGUAL",
  "MOSTRAR",
  "IF",
  "PUNTOYCOMA",
  "IDENTI",
  "INT",
  "DOUBLE",
  "CHAR",
  "BOOL",
  "STRING",
  "DOUBLEN",
  "LETRA",
  "TRUE",
  "FALSE",
  "CADENA",
  "COMENLI",
  "COMENMULTILI"
  };
}

